### ISSUE TITLE
Erro Rest-API

### ISSUE THREAD

**Issue by PauloRenato4** [PauloRenato4/Teste-Rest-API#1]
![capturar](https://cloud.githubusercontent.com/assets/10930418/11314817/7a43b8e2-8fd0-11e5-8e2d-1a42e4c4f1c8.PNG)

@edysegura Edy Porque esta dando este erro? e nao to conseguindo conectar com o front-end, banco esta criado e nao realiza as funções do REST.

**Comment by edysegura** [comment]
Você criou o banco com quantos registros?

**Comment by edysegura** [comment]
Verifique se há registro no banco de dados.

**Comment by PauloRenato4** [comment]
O banco tem 12 registros, verifiquei aqui e consta que  banco foi criado certo

**Comment by PauloRenato4** [comment]
agora deu este erro aqui,  No banco faltava uma virgula, mesmo assim não da puxando os dados..

![image](https://cloud.githubusercontent.com/assets/10930418/11355562/262e6e2c-923d-11e5-8a3a-853beef91f7c.png)

**Comment by edysegura** [comment]
Qual é o link da sua workspace no c9?

**Comment by PauloRenato4** [comment]
link: https://ide.c9.io/paulopaschoal/testar

**Comment by edysegura** [comment]
Bug fixed!

![image](https://cloud.githubusercontent.com/assets/5324414/11356035/ec728bba-9240-11e5-83be-68db80dd496f.png)

**Comment by PauloRenato4** [comment]
OBrigado Edy!
